// android/src/main/jni/react/renderer/components/PrivacyGuardKitViewSpec/
// RNSecureViewComponentDescriptor.h
//
// This file is AUTO-GENERATED by React Native codegen.
// You should NOT edit it manually — re-run codegen to regenerate.
// It is provided here for reference only.
//
// If autolinking.cpp still cannot find RNSecureViewComponentDescriptor,
// ensure your build.gradle has:
//   react {
//     libraryName = "PrivacyGuardKitViewSpec"
//     jsRootDir = file("../src/specs")
//   }
// and run: cd android && ./gradlew generateCodegenArtifactsFromSchema

#pragma once
#include <react/renderer/components/PrivacyGuardKitViewSpec/ShadowNodes.h>
#include <react/renderer/core/ConcreteComponentDescriptor.h>

namespace facebook::react {

using RNSecureViewComponentDescriptor =
    ConcreteComponentDescriptor<RNSecureViewShadowNode>;

} // namespace facebook::react