// RNSecureViewManager.mm
//
// Old Architecture (Paper) ViewManager for RNSecureView.
//
// ── ARCHITECTURE ──────────────────────────────────────────────────────────────
//   Paper path:  JS → RCTUIManager → RNSecureViewManager → RNSecureUIView
//   Fabric path: JS → Fabric renderer → RNSecureViewComponentView
//               (this file is compiled for both but rarely invoked on Fabric)
//
// ── WHY .mm NOT .m ────────────────────────────────────────────────────────────
//   RCT_EXPORT_MODULE and related macros can include C++ expressions in some
//   React Native versions. Using .mm (Objective-C++) avoids compiler errors.
//
// ── COPY/PASTE BLOCKING STRATEGY (Paper) ─────────────────────────────────────
//   RNSecureUIView overrides canPerformAction:withSender: to return NO for all
//   actions when isCopyPasteDisabled is YES, and also recurses into UITextField
//   and UITextView subviews to apply the same protection that the Fabric path
//   provides — giving consistent behaviour across both architectures.
//
// ── SIMULATOR BEHAVIOUR ───────────────────────────────────────────────────────
//   Works identically on the iOS Simulator.
//
// ── iOS VERSION SUPPORT ───────────────────────────────────────────────────────
//   iOS 13+ — canPerformAction:withSender: available since iOS 3.

#import <React/RCTViewManager.h>
#import <React/RCTUIManager.h>
#import <React/RCTConvert.h>
#import <UIKit/UIKit.h>

// ─────────────────────────────────────────────────────────────────────────────
// RNSecureUIView — Paper-only UIView subclass
// ─────────────────────────────────────────────────────────────────────────────
@interface RNSecureUIView : UIView

@property (nonatomic, assign) BOOL isCopyPasteDisabled;

@end

@implementation RNSecureUIView

/**
 * Called by isCopyPasteDisabled's setter (generated by @synthesize / property).
 * Overriding setIsCopyPasteDisabled: lets us trigger the recursive traversal
 * at the moment the prop changes, without requiring the ViewManager to call
 * separate methods.
 */
- (void)setIsCopyPasteDisabled:(BOOL)value {
    _isCopyPasteDisabled = value;
    if (value) {
        [self disableCopyPasteInView:self];
    } else {
        [self enableCopyPasteInView:self];
    }
}

/**
 * Intercepts UIKit's action-availability query at the view level.
 *
 * Returns NO for all actions when isCopyPasteDisabled, preventing the
 * context menu from appearing at this level of the responder chain.
 */
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender {
    if (self.isCopyPasteDisabled) {
        return NO;
    }
    return [super canPerformAction:action withSender:sender];
}

/**
 * Override insertReactSubview:atIndex: to protect late-added children.
 *
 * On Paper, React children are added via insertReactSubview:atIndex: after the
 * initial prop application. Without this override, any child added after
 * isCopyPasteDisabled was set to YES would be unprotected until the next
 * prop update cycle.
 */
- (void)insertReactSubview:(UIView *)subview atIndex:(NSInteger)atIndex {
    [super insertReactSubview:subview atIndex:atIndex];
    if (self.isCopyPasteDisabled) {
        // Protect the newly added subtree immediately.
        [self disableCopyPasteInView:subview];
    }
}

// MARK: - Recursive helpers

/**
 * Recursively disables copy/paste on all UITextField and UITextView descendants.
 *
 * UITextField: userInteractionEnabled = NO
 * UITextView:  selectable = NO, editable = NO (order: selectable first)
 */
- (void)disableCopyPasteInView:(UIView *)v {
    for (UIView *sub in v.subviews) {
        if ([sub isKindOfClass:[UITextField class]]) {
            ((UITextField *)sub).userInteractionEnabled = NO;
        } else if ([sub isKindOfClass:[UITextView class]]) {
            UITextView *tv = (UITextView *)sub;
            tv.selectable = NO;
            tv.editable   = NO;
        }
        [self disableCopyPasteInView:sub];
    }
}

/**
 * Recursively re-enables copy/paste on all UITextField and UITextView descendants.
 */
- (void)enableCopyPasteInView:(UIView *)v {
    for (UIView *sub in v.subviews) {
        if ([sub isKindOfClass:[UITextField class]]) {
            ((UITextField *)sub).userInteractionEnabled = YES;
        } else if ([sub isKindOfClass:[UITextView class]]) {
            UITextView *tv = (UITextView *)sub;
            tv.editable   = YES;
            tv.selectable = YES;
        }
        [self enableCopyPasteInView:sub];
    }
}

@end

// ─────────────────────────────────────────────────────────────────────────────
// RNSecureViewManager — Paper ViewManager
// ─────────────────────────────────────────────────────────────────────────────
@interface RNSecureViewManager : RCTViewManager
@end

@implementation RNSecureViewManager

RCT_EXPORT_MODULE(RNSecureView)

- (UIView *)view {
    return [RNSecureUIView new];
}

/**
 * Handles the `isCopyPasteDisabled` JS prop.
 *
 * RCT_CUSTOM_VIEW_PROPERTY generates a setter the Paper bridge calls whenever
 * the prop changes (including initial render). Delegates to the view's
 * setIsCopyPasteDisabled: which triggers the recursive traversal.
 *
 * DO NOT change the prop name — must match the JS prop and Fabric codegen spec.
 */
RCT_CUSTOM_VIEW_PROPERTY(isCopyPasteDisabled, BOOL, RNSecureUIView) {
    view.isCopyPasteDisabled = json ? [RCTConvert BOOL:json] : defaultView.isCopyPasteDisabled;
}

@end
